/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UwuImport } from './routes/uwu'
import { Route as IndexImport } from './routes/index'
import { Route as ThemeIndexImport } from './routes/theme/index'
import { Route as EditorIndexImport } from './routes/editor/index'

// Create/Update Routes

const UwuRoute = UwuImport.update({
  path: '/uwu',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ThemeIndexRoute = ThemeIndexImport.update({
  path: '/theme/',
  getParentRoute: () => rootRoute,
} as any)

const EditorIndexRoute = EditorIndexImport.update({
  path: '/editor/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/uwu': {
      id: '/uwu'
      path: '/uwu'
      fullPath: '/uwu'
      preLoaderRoute: typeof UwuImport
      parentRoute: typeof rootRoute
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorIndexImport
      parentRoute: typeof rootRoute
    }
    '/theme/': {
      id: '/theme/'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  UwuRoute,
  EditorIndexRoute,
  ThemeIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/uwu",
        "/editor/",
        "/theme/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/uwu": {
      "filePath": "uwu.tsx"
    },
    "/editor/": {
      "filePath": "editor/index.tsx"
    },
    "/theme/": {
      "filePath": "theme/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
